spring:
    data:
        mongodb:
            username: rootuser
            password: rootpass
            host: localhost
            port: 27017
            database: liveproject
            authentication-database: admin
server:
    port: 8010

